[workspace]
name = "masked-stellar-autoencoder"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]
lint = "ruff check ."
format = "ruff format ."
test = "pytest"

[dependencies]
python = "3.12.*"
pytorch = ">=2.1.0"
numpy = ">=1.25.0"
astropy = ">=6.0.0"
pandas = ">=2.1.0"
scikit-learn = ">=1.3.0"
scipy = ">=1.11.0"
h5py = ">=3.10.0"
matplotlib = ">=3.8.0"
tqdm = ">=4.66.0"
pyyaml = ">=6.0.1"
wandb = ">=0.16.0"
ruff = "*"
pytest = "*"

[pypi-dependencies]
masked-stellar-autoencoder = { path = ".", editable = true }
rtdl-num-embeddings = { git = "https://github.com/yandex-research/rtdl-num-embeddings.git", subdirectory = "package" }
